---

- name: "Update local apt repo"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "Remove stale dependencies"
  become: true
  apt: 
    autoremove: yes

- name: "Install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  command: "npm install -g pm2"

# - name: "move env variables to /etc/profile.d/"
#   become: true 
#   copy: 
#     src: myenv.sh 
#     dest: /etc/profile.d/    